sudo: required
services:
  - docker


before_install:
  - docker build -t rg3xists/react -f ./client/Dockerfile.dev ./client

script:
  - docker run rg3xists/react npm test -- --coverage

after_sucess:
  - docker build -t rg3xists/multi-client ./client
  - docker build -t rg3xists/multi-server ./server
  - docker build -t rg3xists/multt-nginx ./nginx
  - docker build -t rg3xists/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rg3xists/multi-client
  - docker push rg3xists/multi-server
  - docker push rg3xists/multt-nginx
  - docker push rg3xists/multi-worker
