sudo: required
services:
  - docker


before_install:
  - docker build -t rg3xists/react -f ./client/Dockerfile.dev ./client

script:
  - docker run rg3xists/react npm test -- --coverage

after_sucess:
  - docker build -t rg3xists/multi-client -f ./client/Dockerfile.dev ./client
  - docker build -t rg3xists/multi-server ./server
  - docker build -t rg3xists/multt-nginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t rg3xists/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rg3xists/multi-client
  - docker push rg3xists/multi-server
  - docker push rg3xists/multi-nginx
  - docker push rg3xists/multi-worker


deploy:
  provider: elasticbeantalk
  region: ap-south-1
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-ap-south-1-908800051602
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access:key: $AWS_SECRET_KEY
